### ISSUE TITLE
API değişikliği

### ISSUE THREAD

**Issue by mhayta** [peshrawahmed/turkeyweather-api#2]
api adresi servis.mgm.gov.tr/web olarak değişmiş ve "server error" "Not allowed by MGM" hatası döndürüyor.

**Comment by peshrawahmed** [comment]
Selamlar, 

Yoğun iş temposundan dolayı cevap verememişim. Kontrol edeceğim, sistemi komple değiştirmemişlerse ayar çekerim. Değiştirmişlerse şimdilik bulursam README.md dosyasına bir alternatif koyarım.

**Comment by peshrawahmed** [comment]
Selamlar Tekrar :)

2 buçuk yıl sonra github repolarımda gezerken bu sorunu basit bir header ekleyerek çözebileceğimizi farkettim. zamanında biz niye kapatmışız bu repoyu? 

Bir allahın kulu da dememiş ki biraz inceleyin çözümü bulacaksınız 😆 

Repoyu bu commitle  (effc18f5d67ea306510d39d609a1e1bc54052369) tekrar aktif ediyorum

Artık hiç PHP yazmıyorum ama hala kullanmak isteyen varsa faydalanabilir.

Herkese iyi çalışmalar
